package rules.Update
dialect "java"
import com.promise.entity.DiscountInformation
rule 'disconut1'
    when
        $d:DiscountInformation(price > 300)
    then
        $d.setPrice($d.getPrice() - 50);
        update($d)
    end

rule 'disconut2'
    when
        $d:DiscountInformation(price > 200)
    then
        $d.setPrice($d.getPrice() - 50);
    end

rule 'disconut3'
    when
        $d:DiscountInformation(price > 100)
    then
        $d.setPrice($d.getPrice() - 50);
    end